apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-weight-and-balance
  labels:
    app: acm-weight-and-balance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-weight-and-balance
  template:
    metadata:
      labels:
        app: acm-weight-and-balance
      annotations:
        linkerd.io/inject: "enabled"
    spec:
      serviceAccountName: acm-weight-and-balance
      containers:
      - name: acm-weight-and-balance
        image: michaelvlaar/acm_weight_and_balance:0.1.19
        ports:
        - containerPort: 80 
          name: http
        - containerPort: 8081 
          name: health-http
        livenessProbe:
          httpGet:
            path: /healthz
            port: health-http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: health-http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "50Mi"
            cpu: "10m"
