apiVersion: v1
kind: Service
metadata:
  name: acm-weight-and-balance
spec:
  selector:
    app: acm-weight-and-balance
  ports:
    - protocol: TCP
      port: 80
      targetPort: http 
  type: ClusterIP
