[package]
name = "acm_weight_and_balance"
version = "0.1.2"
edition = "2021"

[dependencies]
airplane = "0.1.4" 
actix-web = "4"
tera = "1.12"
serde = { version = "1.0", features = ["derive"] }
rust-embed = "6.3.0"
